### PR TITLE
Add support for Swift 5.1 (5.0 impossible due to compiler bug)

### PR DESCRIPTION
**Pull request by slashmo**
Since we plan on introducing `Baggage` as a dependency for `Logging` (https://github.com/apple/swift-log/pull/235) we want to lower our minimum supported Swift version to 5.0 to match `Logging`.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -1,16 +1,21 @@
...
+[![Swift 5.0](https://img.shields.io/badge/Swift-5.0-ED523F.svg?style=flat)](https://swift.org/download/)
+[![Swift 5.1](https://img.shields.io/badge/Swift-5.1-ED523F.svg?style=flat)](https://swift.org/download/)
 [![Swift 5.2](https://img.shields.io/badge/Swift-5.2-ED523F.svg?style=flat)](https://swift.org/download/)
 [![Swift 5.3](https://img.shields.io/badge/Swift-5.3-ED523F.svg?style=flat)](https://swift.org/download/)
 [![Swift 5.4](https://img.shields.io/badge/Swift-5.4-ED523F.svg?style=flat)](https://swift.org/download/)
 [![Swift 5.5](https://img.shields.io/badge/Swift-5.5-ED523F.svg?style=flat)](https://swift.org/download/)
+[![Swift 5.6](https://img.shields.io/badge/Swift-5.6-ED523F.svg?style=flat)](https://swift.org/download/)
+[![Swift 5.7](https://img.shields.io/badge/Swift-5.6-ED523F.svg?style=flat)](https://swift.org/download/)
 
-> ⚠️ Automatic propagation through task-locals only supported in Swift >= 5.5
```
Comment (slashmo) [inline README.md:8]: Changes this to "**Warning**" because it will be highlighted as a warning on GitHub: https://github.com/community/community/discussions/16925

**Comment by ktoso** [comment]
@yim-lee could we ask you to help us out and add 5.0 and 5.1 CI to this project? We want to match what swift-log supports, even it supporting 5.0 is a bit ridiculous at this point 😆

**Comment by yim-lee** [comment]
Added CI for 5.0 and 5.1. @swift-server-bot test this please

**Comment by slashmo** [comment]
> Added CI for 5.0 and 5.1.

Thank you 🙏

**Comment by slashmo** [comment]
5.0 is failing because of what I think is a compiler bug. We have a test which contains conditionally compiled code (`#if swift(>=5.5) && canImport(_Concurrency)`), but it still fails to compile on 5.0:

```
/code/Tests/InstrumentationBaggageTests/BaggageTests.swift:81:17: error: expected numeric value following '$'
        Baggage.$current.withValue(baggage, operation: exampleFunction)
                        ^
```

CI Run: https://ci.swiftserver.group/job/swift-distributed-tracing-baggage-swift50-prb/4/console
Unit Test in question: https://github.com/apple/swift-distributed-tracing-baggage/blob/8ea12077aafca36aa28500adead394b7789b8f5c/Tests/InstrumentationBaggageTests/BaggageTests.swift#L66

File: README.md (hunk 1 above)
Comment (ktoso) [reply README.md:8]: ok cool :)

File: README.md [hunk 2]
```diff
@@ -1,16 +1,21 @@
 # 🧳 Distributed Tracing: Baggage
 
+[![Swift 5.0](https://img.shields.io/badge/Swift-5.0-ED523F.svg?style=flat)](https://swift.org/download/)
+[![Swift 5.1](https://img.shields.io/badge/Swift-5.1-ED523F.svg?style=flat)](https://swift.org/download/)
 [![Swift 5.2](https://img.shields.io/badge/Swift-5.2-ED523F.svg?style=flat)](https://swift.org/download/)
 [![Swift 5.3](https://img.shields.io/badge/Swift-5.3-ED523F.svg?style=flat)](https://swift.org/download/)
 [![Swift 5.4](https://img.shields.io/badge/Swift-5.4-ED523F.svg?style=flat)](https://swift.org/download/)
 [![Swift 5.5](https://img.shields.io/badge/Swift-5.5-ED523F.svg?style=flat)](https://swift.org/download/)
+[![Swift 5.6](https://img.shields.io/badge/Swift-5.6-ED523F.svg?style=flat)](https://swift.org/download/)
+[![Swift 5.7](https://img.shields.io/badge/Swift-5.6-ED523F.svg?style=flat)](https://swift.org/download/)
```
Comment (ktoso) [inline README.md:10]:
```suggestion
[![Swift 5.7](https://img.shields.io/badge/Swift-5.7-ED523F.svg?style=flat)](https://swift.org/download/)
```

**Comment by ktoso** [comment]
Can't seem to be able to workaround the 5.0 issue, even compiler(>=5.5) does not help. We may need to drop 5.0 support tbh.

**Comment by ktoso** [comment]
Talked a lot with the swift team about the bug here -- there does not seem to be a workaround, we can't support 5.0 basically -- even with the compiler guards it still will attempt to lex the task local but will fail doing so.

**Comment by ktoso** [comment]
Discussed this in depth with the Swift team, it is impossible for a library to support any task-local usage and "#if-out" its usage without breaking Swift 5.0, since it will still attempt and fail to lex this piece of "iffed out" code. As such, we cannot support 5.0, nor can any library which _optionally_ (!!!) supports task-locals, because of this compiler bug in 5.0.
